### ISSUE TITLE
[Fix] server_config(nginx.conf) 파일을 indent로 구별하는 방식이 아닌 {} 로 구별하는 방식으로 쓰면 어떻까 싶음

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#10]
## 제안
단순히 말하면 파싱이 어려움! 그래서 {} 가 있는 방식으로 하고 싶음.

## 이유
글로 표현하기가 어려워 슬랙에 남겨봤음.
https://42born2code.slack.com/archives/G01HWCVQS2E/p1619070255018000

## To you
자유롭게 의견 말해주면 좋을 듯.바꿨을 때 안좋은 점이 있는 지 알려주면 좋을 듯

**Comment by kohyounghwan** [comment]
나는 바꿔도 좋다고 봄

우리가 최초에 서로 이슈 생겼을 때, ㅗ포도움 주고 받기 좋게 전체적으로 구조 합의를 하고 시작했는데

맞추면 좋지만 코드 작성하는 사람에 따라서 수정하고 싶은 부분이 생기기마련이고, 

우리쪽에서 이슈가 생겼을때 도움받기 어려울수도 있는데, 그런부분은 어떤부분에서 어떻게 수정되었고 이런부분이 명확하기때문에 이것도 큰 문제 없을것 같음.

**Comment by exgs** [comment]
server_config 형식을 {} 쓰는 것으로 바꿔서 빠르게 서버파싱하는 함수를 작성해보겠음.
