### ISSUE TITLE
[Final] 서브젝트에서 미흡한 사항

### ISSUE THREAD

**Issue by ykoh42** [404-DriverNotFound/200-OK#105]
# 헤더
- [x] Content-Location
	https://runebook.dev/ko/docs/http/headers/content-location
- [x] Last-Modified
- [x] Retry-After
	https://developer.mozilla.org/ko/docs/Web/HTTP/Headers/Retry-After
- [x] ~~ㄴㄹㅁ~~

# config
- [x] make the route able to accept uploaded files and configure where it should be saved
		https://www.nginx.com/resources/wiki/modules/upload/

# CGI
- [x] execute CGI based on certain file extension (for example .php) (php-cgi)
		https://bogyum-uncle.tistory.com/94
- [x] cgi 환경변수
- [x] Your program should call the cgi with the file requested as first argument*

# 기타
- [x] errno 의심살수 있으니 지우는 것도..?
- [x] leaks crash 검사
- [x] config 파일 정리 및 내용 수정
- [x] #130

**Comment by ykoh42** [comment]
위의 항목들빼고 다 어느정도 준수하고 있는듯.

**Comment by exgs** [comment]
---

Content-Location -> 201 New created
Last-Modified -> fstat
  `st_mtime         Time when file data last modified.  Changed by the`
 Retry-After -> (500 <= n) then; 1 minute

---

**Comment by exgs** [comment]
위에 언급된, ㅎㅔ더 작업은 모두 종료함

**Comment by exgs** [comment]
leaks crash 문제는 9782c5b2f7e8f39359f543cbcd290da64c55abdc 에서 해결함.
메모리누수 체크는 leaks로만 함.

**Comment by exgs** [comment]
Config는 사실상 하는 의미가 크지 않은 것 같아서 안하려고 함. @kohyounghwan
