### ISSUE TITLE
[Fix] executeoptions 문제해결

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#108]
**문제점**
생각하는대로 동작하지 않았음 TDD 방식으로 구현함. PR올리고자 함

**테스트 케이스**
1. 파일경로로 접근, 특정 리소스파일 없는 경우, 404
2. 파일경로로 접근, 특정 리소스파일 있는 경우, 해당 location 블록에 allowed method
3. 폴더경로로 접근, 특정 폴더가 있는 경우, 해당 location 블록에 allowed method
4. 폴더경로로 접근, 특정 폴더가 없는 경우, 404
5. 파일경로로 접근, 폴더인 경우 어쩔 수 없이 GET redirection
6. `localhost:8000/directory/*`  특수한 경우
7. `localhost:8000/YoupiBanane/**` 특수한 경우를 꼬은 경우 404 에러

**Comment by exgs** [comment]
test_options.config 로 서버생성후 테스트하면 됨

**Comment by ykoh42** [comment]
`curl -X OPTIONS http://localhost:8000/directory/Yeah/ -i`

`curl -X GET http://localhost:8000/directory/Yeah/ -i`

```
GET http://localhost:8000/directory/Yeah/ -i

HTTP/1.1 404 Not Found
Content-Length: 192
Content-Type: text/html
Date: Thu, 03 Jun 2021 04:27:54 GMT
Server: YKK_webserv

<html><head><title>404 Not Found</title></head><body bgcolor="white"><center>
<h1>404 Not Found</h1></center><hr>
<h2>Method: GET</h2></center><hr>
<center>YKK_Webserver</center></body></html>
```

```
curl -X OPTIONS http://localhost:8000/directory/Yeah/ -i

HTTP/1.1 200 OK
Allow: OPTIONS GET
Content-Length: 0
Date: Thu, 03 Jun 2021 04:28:27 GMT
Server: webserv
```

두가지 결과가 같아야 할것같은데 상이함 option에서도 404가 떠야할것같음
