### ISSUE TITLE
[Fix: jikang branch] Makefile 목적파일 중복 생성

### ISSUE THREAD

**Issue by PennyBlack2008** [404-DriverNotFound/200-OK#13]
**문제점**
https://github.com/404-DriverNotFound/200-OK/tree/jikang 의 이슈입니다.
Make 시 srcs 경로와 Makefile 파일이 있는 경로에 동시에 목적파일이 만들어짐

**예상되는(제대로 된) 동작**
Make 시 srcs 경로에만 목적파일이 생겨야한다.

**해결 방법(optional)**
Makefile 을 수정한다. 특히 목적파일 만드는 부분

**버그 재현 방법(버그를 발생시키는 방법)**
단계 별로 기술해주세요.
1. Makefile 파일이 있는 경로에서 make 를 한다.
2. 목적파일이 ./srcs 파일 경로와 Makefile 경로에 모두 있는 것을 확인한다.

**Comment by exgs** [comment]
```
$(NAME)	:	$(OBJS)
			# $(CC) -c $(SRCS)
			$(CC) -o $(NAME) $(OBJS)
```
주석 처리하는 것으로 해결 할 수 있습니다.

**Comment by PennyBlack2008** [comment]
issue#13 fixed by exgs
