### ISSUE TITLE
[Fix] 1회 request를 받고 종료되는 문제

### ISSUE THREAD

**Issue by kohyounghwan** [404-DriverNotFound/200-OK#15]
**문제점**
서버는 요청을 계속 받을 수 있도록 대기하여야 하는데, 현재 1회 요청을 받고 종료됨.

**예상되는(제대로 된) 동작**
단일 클라이언트에서 http request를 보내면 보내는 족족 받을 수 있어야 함(프로그램이 종료되지 않고)

**해결 방법(optional)**
read를 loop를 걸고 fcntl로 non blocking 처리해야함

**버그 재현 방법(버그를 발생시키는 방법)**
생략

**Comment by kohyounghwan** [comment]
@PennyBlack2008
버퍼사이즈를 몇으로 해야할지 잘 모르겠어서 버퍼 사이즈에 상관없이 동작하면 좋을 것같음 지금은 최대 2^16정도 버퍼가 될것같은 느낌이 듦.

그리고 fcntl적용하면 상황에 따라 
처음 읽을때 -1이 반환되는 경우가 있었던것같음

**Comment by exgs** [comment]
나도 관련주제에 관심이 있음. 도울 수 있는 부분이 있을 수 있을 것 같음
