### ISSUE TITLE
[Refactor]:  Accept() 함수

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#27]
`client_socket = socket_one.Accept(client_socket);`

Accept 함수에서 `int client_socket` 를 인자로 받는데, 동작에 영향을 미치는 요소가 아니기 때문에, 함수내에 지역변수로 넣으면 좋을 꺼 같음.

@PennyBlack2008

**Comment by PennyBlack2008** [comment]
이슈 확인했음. 그렇게 하겠음.
