### ISSUE TITLE
Docs: "Launch multiple server at the same time with different configuration but with common ports."

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#38]
### Port issue
Launch multiple server at the same time with different configuration but with common ports. Is it working? if it is working, ask why the server should work if one of the configuration isn't working. Keep going

   실행이 되지 않아야 맞는 것인데, 실행이 되도록도 할 수 있는 건가?

**Comment by ykoh42** [comment]
이건 매우 애매한데 우선 설정파일 관련해서

nginx는
listen 모듈로 호스트랑 포트 를 작성해서

동작할수있는데 이것으로 가능하게 동작할수있는것같음

http://nginx.org/en/docs/stream/ngx_stream_core_module.html#listen

우리도 host:port로 동작해야하는데

host부분은 없는것같음

host :port로 동작한다면 서버 1개당 서버객체 하나 이렇게 매칭할수있을듯

**Comment by exgs** [comment]
config 파일에 host 요소를 추가함으로써 해결함. #77 

---

port별로 잘 알려져 있는 포트, 등록된 포트, 그외의 포트 이렇게 세가지로 구분된다.
https://ko.wikipedia.org/wiki/TCP/UDP%EC%9D%98_%ED%8F%AC%ED%8A%B8_%EB%AA%A9%EB%A1%9D
잘 알려져 있는 포트와 등록된 포트로 연결하지 않도록 하는 것이 강제적인 것이 아니라 IANA의 권고사항이라고 한다.
그리고 nginx에서도 이러한 포트로 잘 열리기 때문에, 예외처리는 하지 않도록 한다.
