### ISSUE TITLE
[Feat] location block 파싱

### ISSUE THREAD

**Issue by kohyounghwan** [404-DriverNotFound/200-OK#4]
ㅇㅅ1

**Comment by kohyounghwan** [comment]
파싱잘완료되서 이슈클로스하면!?

**Comment by exgs** [comment]
## location 블록 중첩 문제
**문제점**
location block안에 location block이 있는 server_config 파일이 있을 수 있음.
**예상되는(제대로 된) 동작**
nginx 같은 웹서버에서는 location 블록 안에 location 블록 까지 읽기도 함.
 하지만, location 중첩을 하더라도 일반적으로 생각하는 방향과 다르게 동작하는 경우가 있다고 함. (2014) https://kjwon15.net/wordpress/articles/computer/configure/262
**해결 방법(optional)**
우리의 webserver config 파일은 최대한 단순하게 만들고, 형식을 엄격하기 지키도록 강제하도록 룰을 정한다면,
location의 중첩을 에러로 판단하면 문제를 해결(회피)할 수 있다.
