### ISSUE TITLE
Docs: "limit client body size"

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#40]
Configuration
1. limit the client body (use curl -X POST -H "Content-Type: plain/text" --data "BODY IS HERE write something or longer than body limit")

client body가 서버의 response의 바디인가 서버의 request의 바디인가.
content-length가 엄청 커졌을 때, 문제가 되는 부분을 config파일에서 client-body 값으로 제한해주면, 문제가 안 생기는 건가?

**Comment by ykoh42** [comment]
configuration 파일에서 
◦ limit client body size

요게 정상적으로 작동하는지 확인하는 문구 같음
그렇다면 request body일듯
