### ISSUE TITLE
[Fix] 테스터돌리기!

### ISSUE THREAD

**Issue by ykoh42** [404-DriverNotFound/200-OK#61]
# 테스터 돌리기
테서터 통과를 위한 이슈!
## 테스트 케이스
```
Test GET http://localhost:80/
Test POST http://localhost:80/ with a size of 0
Test HEAD http://localhost:80/
Test GET http://localhost:80/directory
Test GET http://localhost:80/directory/youpi.bad_extension
Test GET http://localhost:80/directory/youpi.bla
Test GET Expected 404 on http://localhost:80/directory/oulalala
Test GET http://localhost:80/directory/nop
Test GET http://localhost:80/directory/nop/
Test GET http://localhost:80/directory/nop/other.pouic
Test GET Expected 404 on http://localhost:80/directory/nop/other.pouac
Test GET Expected 404 on http://localhost:80/directory/Yeah
Test GET http://localhost:80/directory/Yeah/not_happy.bad_extension
Test Put http://localhost:80/put_test/file_should_exist_after with a size of 1000

==================================================================
the file file_should_exist_after should have been created with a size of 1000 bytes. Check that now
==================================================================
Test Put http://localhost:80/put_test/file_should_exist_after with a size of 10000000

==================================================================
the file file_should_exist_after should still be there but this time with a size of 10000000 bytes. Check that now
==================================================================
Test POST http://localhost:80/directory/youpi.bla with a size of 100000000
Test POST http://localhost:80/directory/youpla.bla with a size of 100000000
Test POST http://localhost:80/directory/youpi.bla with a size of 100000 with special headers
Test POST http://localhost:80/post_body with a size of 0
Test POST http://localhost:80/post_body with a size of 100
Test POST http://localhost:80/post_body with a size of 200
Test POST http://localhost:80/post_body with a size of 101

Test multiple workers(5) doing multiple times(15): GET on /

Test multiple workers(20) doing multiple times(5000): GET on /

Test multiple workers(128) doing multiple times(50): GET on /directory/nop

Test multiple workers(20) doing multiple times(5): Put on /put_test/multiple_same with size 1000000

==================================================================
the file multiple_same should exists with a size of 1000000 bytes. Check that now
==================================================================
Test multiple workers(20) doing multiple times(5): Post on /directory/youpi.bla with size 100000000
```

## 최소 요구사항 configuration 파일
```
# Setup the configuration file as follow:
server
{
# - any file with .bla as extension must answer to POST request by calling the cgi_test executable
	cgi_extension .bla
	port 8000

# - / must answer to GET request ONLY
	location /
	{
		method GET
	}

# - /put_test/* must answer to PUT request and save files to a directory of your choice
	location /put_test/*
	{
		method PUT
	}

# - /post_body must answer anything to POST request with a maxBody of 100
	location /post_body
	{
		method POST
	}
	
# - /directory/ must answer to GET request and the root of it would be the repository YoupiBanane and if no file are requested, it should search for youpi.bad_extension files
	location /directory/
	{
		method GET
		root YoupiBanane
		index youpi.bad_extension
	}
}
```

**Comment by ykoh42** [comment]
# 테스터 이슈
## 1. broken pipe
테스터가 write broken pipe라면서 꺼짐
### Case
```
Test multiple workers(20) doing multiple times(5000): GET on /
```
### 원인
깨진 fd에 뭔가를 보내려고 했을 때 발생하는 것같다.  
발생한 이유는 모르겠음

### 해결방법
응답을 보내면 커넥션을 끊어줬는데 이 부분을 안끊게 수정함

***커넥션이 끊키는 조건***
1. read 0반환

## 2. 테스트케이스가 진행되지 않는 문제
아래케이스 다음으로 테스트가 진행되지 않았다. 테스터 서버 둘다 계속 살아있었음
### Case
```
Test POST http://localhost:80/directory/youpi.bla with a size of 100000000
```
### 원인
서버쪽에서 먼저 커넥션을 끊어주는 경우가 없어서 발생한 문제다.  
서버쪽에서 커넥션을 끊어주기를 바라는 케이스인 것같음.  

### 해결방법
일정시간동안 읽을것도 쓸것도없다면 끊어준다

***커넥션이 끊키는 조건***
1. read 0반환
2. 일정시간동안 읽을것도없고 쓸것도 없는 상태

## 3. EOF
`FATAL ERROR ON LAST TEST: Get http://localhost:8000/: EOF` 라고 나옴

### Case
```
Test multiple workers(128) doing multiple times(50): GET on /directory/nop
```
### 원인
테스터에서 아직 연결만하고 아무것도 안했는데 서버측에서 클라이언트 소켓을 먼저 끊어줘서 테스터가 eof라고 얘기하는것같음

잘모르겠으나, 워커를 먼저 추가한다음 데이터를 한방에 쏴준다고 가정했을떄,
워커가 추가되는 과정에서 타임아웃떄문에 커넥션이 끊기는게 아닐까..?

### 해결방법
아직 모르겠음
<img width="676" alt="Screen Shot 2021-05-25 at 2 45 48 AM" src="https://user-images.githubusercontent.com/16534576/119387038-52678680-bd03-11eb-9ca8-97d130f65e5b.png">
위 사진을 보면 readset에 있는녀석들이라 끊어버리면안되는데 시간초과로 끊키는것같다 이부분 해결못함

**Comment by exgs** [comment]
Before starting please follow the next few steps (files content can be anything and will be shown to you by the test):
- Download the cgi_test executable on the host
- Create a directory YoupiBanane with:
	-a file name youpi.bad_extension
	-a file name youpi.bla
	-a sub directory called nop
		-a file name youpi.bad_extension in nop
		-a file name other.pouic in nop
	-a sub directory called Yeah
		-a file name not_happy.bad_extension in Yeah
press enter to continue

Setup the configuration file as follow:
- / must answer to GET request ONLY
- /put_test/* must answer to PUT request and save files to a directory of your choice
- any file with .bla as extension must answer to POST request by calling the cgi_test executable
- /post_body must answer anything to POST request with a maxBody of 100
- /directory/ must answer to GET request and the root of it would be the repository YoupiBanane and if no file are requested, it should search for youpi.bad_extension files

**Comment by exgs** [comment]
nginx에 따라서 폴더 구성을 directory 폴더안에 sub 폴더가 있는 것을 제외하면 모든 조건을 충족하는 것으로 보임
webserv 평가가 모두 끝날 때 까지는 남겨두는 편이 좋을 것 같아서 남겨두지만, 문제가 없기 때문에 bug label 을 제거함

**Comment by exgs** [comment]
+tester 에서 POST에 관련된, body는 chunked로 request를 보내는 것으로 보인다.

**Comment by exgs** [comment]
+케이스 설명
Test POST http://localhost:80/post_body with a size of 0
리디렉션 301 => GET http://localhost:80/post_body/ => autoindex 200
