### ISSUE TITLE
[Fix] 요청 리소스가 파일인지 아닌지, 그에 따라 리디렉션을 할지 말지

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#70]
**문제점**
요청 리소스가 파일인지 아닌지는 마지막에 `/` 가 붙는지 아닌지에 따라 달라진다.
https://djkeh.github.io/articles/Why-do-we-put-slash-at-the-end-of-URL-kor/

---

nginx 테스트이미지
<img width="1452" alt="Screen Shot 2021-05-28 at 2 33 40 PM" src="https://user-images.githubusercontent.com/56223639/119937723-43642b00-bfc6-11eb-9183-817b7b1fac3a.png">

nginx에서 `http://localhost:8080/yunslee` 로 접근하면, 존재는 하지만 폴더이기때문에 301 리디렉션을 보내주고 다시 `/` 를 붙여서 다시 요청을 한다. `http://localhost:8080/yunslee/` 이렇게 접근했을 때는 index 로 설정된 파일이 yunslee 폴더안에 존재하기 때문에 200을 보내주는 모습이다.

**예상되는(제대로 된) 동작**
예를 들면, 테스터기에서 `Test GET Expected 404 on http://localhost:80/directory/oulalala` 이 경우에서 oulalala를 폴더로 인식하기 때문에, 좀 아쉬움.
만약 파일로 인식하게한다면, 또 다른 문제가 발생하는데 Test GET Expected 404 on http://localhost:80/directory 에서 일반적인 동작방식은 다음과 같다.
1. 우선은 파일로 인식한다.
2. 파일로 인식하고 존재를 보았는데, 폴더로써 존재하면, 301 page를 보내고, 뒤에 `/` 를 붙여서 리디렉션을 한다.
3. 폴더 파일 둘다 존재하지 않으면, 404 에러를 발생시킨다.

**해결 방법(optional)**
6월1일 이후에, 파일의 존재 유무나 디렉토리인지 파일인지를 알려주는(`access()`) 함수가 추가되면 고치는 것을 시도해볼 수 도 있을 것 같음.
(현재 ft::access() 함수를 만들기는 하였으나 완전하게 동일하는지 테스트를 해보지는 않았음)
우선 파일인지 디렉토리인지를 현재 확장자명에서 판단하고 있음. 이 방법도 나쁘지 않고 우리가 만든 웹서버에서 이렇다고 주장할 수 있음.

**문제상(버그를 발생시키는 방법)**
단계 별로 기술해주세요.
1. 테스트를 진행하기 전에 Fix/ContentLength Branch에서 Parret! 커밋에서 /YoupiBanane/oulalala 폴더를 삭제시킨뒤에 tester를 돌리면 테스터를 통과하지 못한다.

Related to: #61

**Comment by exgs** [comment]
<img width="1508" alt="Screen Shot 2021-05-28 at 3 10 40 PM" src="https://user-images.githubusercontent.com/56223639/119938118-e026c880-bfc6-11eb-9664-acde6a893a5d.png">

확장자가 아니라 `/` 를 기준으로 나누어준다면, 이런식으로 수정해야하고, configfile과의 조합에서 매우 복잡해짐
localhost:8000/directory => 파일로 본다면,

default.conf 파일안에
````
location directory/ {} 
````
이 경우에 폴더로 판단하지 않기때문에 해당 로케이션에 들어가지 않아야하는지...가 1번
````

location directory {}
location directory/ {}
````
이런 식으로 구분을 해주어야하는지... 가 2번
nginx와 비교해서 맞춰줘야하는지...가 3번

**Comment by ykoh42** [comment]
#51
