### ISSUE TITLE
[Refactor]: 최적화, max_fd를 계산하는 부분을 함수에 의존하지 않기 

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#71]
**기능이 필요한 이유**
select의 첫번째 인자에 넣어주는 fd_max 값을 찾기 위해서 `resetMaxFd()`함수에서 반복문을 돌면서 fd 최대값을 찾고 있다. 이 부분에서 성능저하가 예상되어서 디버깅을 하고자 함
![20210528_154416225](https://user-images.githubusercontent.com/56223639/119941769-fc793400-bfcb-11eb-8e5c-ccd3d603acdb.jpg)
책에서 언급된 것처럼 윈도우의 소켓핸들과는 다르게 리눅스의 파일디스크립터는 +1 씩 생성되는 규칙이 있어서, max_fd 와의 관계성을 찾아 낼 수 있다. 이 부분을 이용하고자함.

**솔루션(optional)**
공통사항: 소켓을 생성할 때마다 비교해서 갱신해주고, close 할때 비교하고 일치하면 삭제해주기
1. m_fd_max 변수값에 최대값을 저장해주기보다는, vector에서 sort()을 해주고 맨 마지막 값을 쓰는 걸로
2. m_fd_max 변수가 값에 담아주고, close() 할 때 해당 fd가 m_fd_max와 일치하면, 그때 read_ 탐색해서 
3. 아예 literal로 150 값을 담는게 더 빠를 꺼 같기도 함.
4. 새로 생성된 Fd > 갯수 일 때만 갱신해주기 이때, fd값이 큰 녀석이 끝까지 버티고 있는 경우면 매우 비효율적이긴하나, closdOldconnection에서 reset 해주는 과정이 있으니깐 이 프로젝트에서는 해당사항이 없을 것 같음

**Comment by ykoh42** [comment]
sort가 들어가면 1회순회하는것보다 성능이 저하될 가능성이 있을것같음

단순히 연결되면 fd가 열리면 +1 닫히면 -1 이런식으로 하면 엄청 좋지않을까싶었는데

웹서버말고 다른 프로그램에서도 fd를사용할수있으니 이건조금 어려울것같고....

**Comment by exgs** [comment]
1. 현재 방식
  <img width="860" alt="원본" src="https://user-images.githubusercontent.com/56223639/120093157-52c4af00-c153-11eb-8294-3726060e4ad3.png">
2. select의 첫번째인자에 150 값 고정하기
  <img width="875" alt="고정값" src="https://user-images.githubusercontent.com/56223639/120093171-6708ac00-c153-11eb-92c3-cee53aae1eea.png">
3. open, accept로 생성될때, maxFd++를 해주고 client가 전부다 끊어질 때, (2 + 서버소켓의 갯수) 로 초기화하기
  <img width="863" alt="mTotalClients" src="https://user-images.githubusercontent.com/56223639/120093193-88699800-c153-11eb-95c8-1d5d03636474.png">

---

### 실험 결과
3번째 것이 그나마 좀 나긴하다. 그러나 효과는 매우 미미하다.

**Comment by exgs** [comment]
4. 3번에서 클라이언트의 총 갯수를 mTotalClients ServerManager의 멤버변수로 세어주고있었다. 전역변수로하면 조금 더 빨라지지않을까하는 생각에 추가 작업을 진행함.
<img width="863" alt="gTotalClients" src="https://user-images.githubusercontent.com/56223639/120093523-d67f9b00-c155-11eb-954a-1b1a3e354b22.png">
조금 더 빨라지긴했으나 역시나 미미함.

---

어쩌면 Get함수는 이미 한계에 다다른 초고속으로 달리고있고, tester에서 3분이 걸리는건 알다시피 마지막 케이스에서 거의 2분 40초를 사용하기 때문인데, 이것은 파일로 저장하는 문제나, std::string에 담는 구조적인 문제여서 tester를 더 빠르게 최적화하는것은 시간이 오래걸릴 수도 있겠다는 생각이 든다.
@kohyounghwan

**Comment by exgs** [comment]
그래도 네가지 테스트중에서 가장 빠른 케이스인 4번, 전역변수를 사용하는 것으로 커밋 및 PR을 하고자함.
속도를 높이고자하는 측면에서 전역변수를 사용한 것이기 때문에 이유는 충분하다고 생각됨

**Comment by exgs** [comment]
Merge 후 반영되었기 때문에 이슈를 닫는다

**Comment by exgs** [comment]
closes: #71
