### ISSUE TITLE
[Refactor] camelcase로 수정

### ISSUE THREAD

**Issue by ykoh42** [404-DriverNotFound/200-OK#75]
camelcase로 수정하기

**Comment by exgs** [comment]
거의 90% 정도로 카멜케이스로 수정한 것으로 알고 있다.
향후 보일 때마다 수정해주면 되는 것으로 생각해서, close 하도록 한다.
(혹시 조금 아쉽다면, 해당 reopen을 한 뒤에 고치는 걸로 하자!)
