### ISSUE TITLE
[Rule] true, false, success, fail, error

### ISSUE THREAD

**Issue by exgs** [404-DriverNotFound/200-OK#9]
아래와 같은 매크로 변수 쓰는 것을 건의함.

```
#define TRUE 1
#define FALSE 0

#define SUCCESS 1
#define FAIL 0
#define ERROR -1
```

**Comment by exgs** [comment]
fail 이랑 error 랑 의미가 겹치는 것 같긴 함. error를 없애고
SUCCESS, FAIL 만 쓰는게 좋을 수도 있을 것 같음

**Comment by kohyounghwan** [comment]
깃허브에 디스커션항목도 있는데 그거 열까?
복잡하면 이슈에만 해도 상관없긴함 ㅎㅎ

뭔가 반환값을 사용할 때를 위해서 단순히 true false 만 표현하는 것말고 error인 상황도 반환해주어 따로 처리해주기 위해 사용될 매크로들 같고,

```
#define TRUE 1
#define FALSE 0
```
위의 매크로는 필요없을 것같아 boolean type을 사용하면 될것같아서 이미 true false를 표현할 수 있는 것이 있기 때문에

```
#define SUCCESS 1
#define FAIL 0
#define ERROR -1
```
나는 define해서 잘 사용하지는 않는데, 그 이유가 기본 라이브러리 함수들이 실제 반환하는 값들은 1 0 -1로 반환할지라도 
man page를 보면 반환을 정의하기를  보통 `1` `0` `-1` 로 표현하지 않고 `양수` `0` `음수` 이렇게 세가지로 나누어서 사용하는 경우가 많아서 특정한 값을 딱 지정해서 매크로로 만들어서 사용하지는 않는 편임

뭔가 표현이 명확해진다면 이번 기회에 나도 매크로로 정의해서 사용해보는 것도 좋을것같음

**Comment by exgs** [comment]
애매하면 안쓰는 걸로!, boolean 자료형 쓸 수 있는  true, false는 나는 왕왕 이용할 것 같음.
