### ISSUE TITLE
[Feat] Auth 비슷하게라도 구현하기

### ISSUE THREAD

**Issue by ykoh42** [404-DriverNotFound/200-OK#90]
**기능이 필요한 이유**
WWW-Authenticate
Authorization
401, 403 status code 구현에 필요함

참고 자료
https://extrememanual.net/12314
https://developer.mozilla.org/ko/docs/Web/HTTP/Authentication

**솔루션(optional)**
1. configuration 파일에 아래와 같은 느낌의 설정 추가
```
 auth_basic "message"; # 로그인 팝업창 메시지
 auth_basic_user_file /etc/nginx/.htpasswd; # 로그인시 필요한 사용자 계정과 비밀번호 정보 파일
```
2. 아래의 인증과정대로 수행
## 인증 과정
<img width="1254" alt="Screen Shot 2021-05-31 at 9 14 25 PM" src="https://user-images.githubusercontent.com/16534576/120191665-2e50fb80-c255-11eb-98ab-0d1ef4f30553.png">

**Comment by ykoh42** [comment]
실제와는 다르지만 우리서버에 가지고 있는 파일에 base64로 인코딩된 상태의 값을 넣는 것으로 함

base64구현하는걸 또 학습해야해서.. 귀찮은 쁀

**Comment by ykoh42** [comment]
Feat/Auth 브랜치에서 작업듕

**Comment by exgs** [comment]
edeb16e0f437f055c7cfea8e487b761b4c699104

./webserv default_auth.config 를 돌린 후, localhost:8000/html 로 접근한다
