### ISSUE TITLE
[Fix] select당 read write 한번이 과연 모든 fd에 적용되야 하는 것일까?

### ISSUE THREAD

**Issue by ykoh42** [404-DriverNotFound/200-OK#93]
**문제점**
select당 read write 한번 룰이 있는데, 이게 소켓에 관련된 fd에만 적용하는것이 맞는것인지

아니면 모든 fd를 포함하는게 맞는 것인지 의문이다.

select가 소켓프로그래밍을 위한 함수 아니던가!

그러므로 소켓 fd에 대해서만 생각하는 것이 맞지 않을까?

현재 같은 경우 최악의 경우 한 턴에 최대 3회까지 read or write를 수행한다.
ex) request 읽을 때 한번, get요청일시 요청한 파일의 데이터를 가져올때 한번, auto인증일치여부를 확인할 때 한번 총 3번 사용한다.

그렇다면 처음에 config도 fd를 사용하는 것이니 이것도 select를 거쳐서 수행해야하는 것일까?

그말은 fdset에 넣어야 한다는 말일까??

**Comment by ykoh42** [comment]
select가 클라이언트당인가 전체당인가!

**Comment by exgs** [comment]
select()라는 함수가 socket 을 관측하는 함수라는 측면에서, 우리는 결론을 내렸다.
select() 함수를 한번 거치면 client에서 송수신에 대한(=소켓의 fd) read or write를 한번만 하는 것으로 결론지었다.
다시말하면, IPC를 위해서 open()으로 파일을 열어서 쓰고 읽는 것은 위 경우에서 카운트하지 않는다고 봤다.(파이프도 마찬가지)

**Comment by exgs** [comment]
+추가
만약에, cgi 처리를 하는 경우에 IPC를 위해서 read write를 하는 경우를 생각해보면, 부모프로세스와 자식프로세스간의 전달해야하는 데이터의 크기가 큰 경우 fork()로 자식프로세스를 생성시키고서 소멸되지않은 상태로 부모프로세스에서 select() 함수가 돌도록 한다는 것인데, 프로세스는 생성 시점 이후로 독립적이라는 측면에서 관리가 불가능거나 어려울 것으로도 보인다.
